#!/usr/bin/env python
"""Subclass of main_frame, which is generated by wxFormBuilder."""

import wxPythonXtras
import frames
import thread
import about_frame_child
import app_methods

# Implementing main_frame
class main_frame_child( frames.main_frame ):
	def __init__( self, parent ):
		frames.main_frame.__init__( self, parent )
		self.Center()
		self.Show()
	
	# Handlers for main_frame events.
	def OnSplit( self, event ):
		thread.start_new_thread(app_methods.Splitter, (self.file_box.GetLabel(), self.output_folder_box.GetLabel(), self.lines_box.GetLabel(), self.text_display, self.progress_bar, self.split_button))
	
	def OnOpenFile( self, event ):
		try:
			filename = wxPythonXtras.OnOpenFile(self)
			self.file_box.SetLabel(filename)
			self.file_size_diplay.SetLabel(str(app_methods.GetFileSize(filename)))
			thread.start_new_thread(app_methods.GetNumberOfLines, (self.lines_label, filename))
			thread.start_new_thread(app_methods.FilePreview, (self.text_display, filename))
		except Exception:
			pass
		
	def OnOutputFolderSelect(self, event):
		try:
			self.output_folder_box.SetLabel(wxPythonXtras.OnSelectFolder(self))
		except Exception:
			pass
	
	def OnExit(self, event):
		self.DestroyChildren()
		self.Destroy()
	
	def OnAbout( self, event ):
		self.Disable()
		about_frame_child.about_frame_child(self)
		
	
	
